### PR TITLE
Display start time for each entry in the log

### PR DESCRIPTION
**Pull request by MaT1g3R**

### CODE REVIEW

**Comment by overshard** [comment]
I agree with being able to see start times for each but i'm not sure I like the design of just adding it into the same block as the time logged like this.

**Comment by MaT1g3R** [comment]
I agree this is not good looking, maybe we can have a toggle mode, where one shows duration and the other shows start and end time?

**Comment by overshard** [comment]
I could see some kind of tooltip working maybe, it's something I'll need to think about a bit, it would be useful to see start times, we have that data.

**Comment by MaT1g3R** [comment]
I think a tooltip might not be the best way to display this information. 
Having a view where you can see all start and end times without having to hover over each entry is very helpful in my opinion.

**Comment by overshard** [comment]
Maybe a customizable "table" like interface where you can select what columns to show? This would allow people to show what information they like and hide information if it's too much for their screen size. I'm not sure how much "customization" I want to add though since I want this to be as simple as possible.

**Comment by MaT1g3R** [comment]
I think just having a toggle button or even a field in a config somewhere should be good enough if having custom columns is too complex.

**Comment by overshard** [comment]
Going to go ahead and merge this and clean it up, thanks for the PR!

**Comment by overshard** [comment]
Design has been improved, thanks again for this, let me know if you'd like additional changes.

**Comment by MaT1g3R** [comment]
Thank you, it looks great!

**Pull request merged**
