### PR TITLE
highlighting entries in log

### PR DESCRIPTION
**Pull request by domind**
Added highlighting of entries in log - right now you can move between entries with arrow up and down.
Would appreciate some feedback. I'm mainly concern abt visual aspect, might be instead of changing background color we should fix like 5px border around entry and change it color between black and fifth color of theme?

### CODE REVIEW

**Comment by overshard** [comment]
I'm reviewing this now and seem to be running into a few bugs. I'll add some comments and request some changes here soon.

**Comment by domind** [comment]
@overshard Hi, finally manged to get some time to fix issues that I was aware. Hope now all will be OK.

**Comment by overshard** [comment]
Maybe I'm missing something? I'm checking the latest deploy on now https://timelite-uyi2j6wd6.now.sh/ but I can't seem to change the current entry via arrow keys? I'll play around with it a bit more this weekend.

**Comment by domind** [comment]
Problems with focus mos likely. Once you click on log area it will start to work. Will try to check it before weekend to fix also this.

**Comment by domind** [comment]
Hi @overshard,
Hope after last commit you will find this satisfactory. Not sure if will have time to work on this further in nearest time due to personal reasons.
Present status:
all should work but following issues exists:
- when changing to log or about pages - focus is lost and click on screen or tab keypress is needed to reactivate shortcuts
- after editing entry - when exiting with "Enter" - focus is lost, but after click hotkeys are recognizing next keys as newKey+Enter, so not working properly, only after hitting enter once again it starts to work again. Added second shortcut for this action alt+s - then only focus is lost. Might be better to deactivate Enter as submitting even if this is most convenient option.
- after editing entry and exiting with arrow - again focus is lost, and after refocusing arrow key is added to pressed one.
- at present moment some actions are global, and there is no notification that it worked. Like you can clear log when in timer screen or reset timer in log or about screens - it will be needed to or add toast with proper info or to limit it to specific screen (like arrows or log edit).

As you can see tried to fix this focus issues with refs, as this worked for timer screen, but for some reason it does not work there. Not sure where is problem. Also this stuck keys - guess there might be some problem with this library I used so eagerly. 

Leaving for time being `logLevel:` in  `'debug'` mode so you can see easier this problems.

**Comment by overshard** [comment]
@domind thanks for the hard work on this! I'll work on the merge conflicts and we can get this integrated and take things from there.

**Comment by domind** [comment]
@overshard Hi, finally had some time to work more on this. Managed to find solutions for lost focus, and problem with "Enter" key. Had to remove  <CSSTransition> and <Transition> as this elements were causing HotKeys to lose focus.

**Comment by overshard** [comment]
Awesome! I'm resolving conflicts now and merging.

**Pull request merged**
