### PR TITLE
Put the clear button at the top

### PR DESCRIPTION
**Pull request by insulatir**

### CODE REVIEW

**Comment by overshard** [comment]
This doesn't seem to do with the commit and PR say it does?

**Comment by insulatir** [comment]
I make PR correctly

**Comment by overshard** [comment]
This is now correct one last change is that I'd make it inline with the tags, them all in one row (except on mobile), since it looks weird otherwise, see screenshot.

offset

**Comment by insulatir** [comment]
You mean like this?
image

**Comment by insulatir** [comment]
I get the clear button inline with filter buttons.

**Comment by overshard** [comment]
I'm getting an overlap on mobile.
timelite-hdvos7nc3 now sh_log(iPhone 6_7_8)

**Comment by insulatir** [comment]
image

I think There is no room for clear button with mobile on my solution. Then It is better to put button above filter buttons.

**Comment by overshard** [comment]
I'm going to go ahead and merge this and clean it up from there, thank you for the update!

**Pull request merged**
